### ISSUE TITLE
ExchangePolicyCleaner for iOS 6

### ISSUE THREAD

**Issue by avibrazil** [joedj/ExchangePolicyCleaner#2]
Would you please provide an update for this package on iOS 6 ?

I can see your cyscript alternative but I have no idea how to use it in an automatic way, I mean, how to install it and forget forever about maintaining it.

Thank you very much.

**Comment by joedj** [comment]
Are you experiencing problems on iOS6?  I believe that it should already be working, and some users have reported as much, though I haven't yet been able to test it myself.

**Comment by joedj** [comment]
Works fine on my iPhone4 and iPad2 with iOS 6.1.  It even automatically refreshed the Exchange policies upon installation, so I didn't have to disable/reenable or delete/recreate my accounts.
