### ISSUE TITLE
Verify iOS 9.0 Compatibility

### ISSUE THREAD

**Issue by jimbair** [joedj/ExchangePolicyCleaner#5]
Just wanted to see if there are any known issues with iOS 9 compatibility or if it should be good to go? The package still only states up to iOS 8.

The only caveat I've seen would be if it's compiled as 32-bit as noted by Saurik here: https://twitter.com/saurik/status/654198997024796672

If it _should_ work, I can install it and report back.

Thanks!

**Comment by brogers5** [comment]
For what it's worth, I've had 1.2-3 installed on my iPhone 6S Plus running iOS 9.0.2 for a couple weeks now, and I have yet to experience any problems.

**Comment by joedj** [comment]
Hrm, sorry, I never saw this github issue.

It should be fine on iOS9/64bit, I've been using it too.

It hooks into `dataaccessd`, which is a 64bit process on 64bit CPUs, so the page size problem saurik noted is not an issue here.
